### ISSUE TITLE
aws-alb-ingress-controller need acm support

### ISSUE THREAD

**Issue by jansony1** [nwcdlabs/kops-cn#4]
If you try to deploy aws-alb-ingress-controller in bjs&zhy region, it will need acm service. While ACM is not currently supported in ZHY&BJS YET.

The issue link in aws-alb-ingress-controller project is right here:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/439

**Comment by walkley** [comment]
This issue has been fixed in release 1.0.0, it does not require ACM anymore. Both HTTP and HTTPS listeners are created successfully by ingress controller, although we have to set IAM certificate ARN for  HTTPS listener in ingress annotation. Following is sample annotations in ingress to setup HTTPS listener:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws-cn:iam::123456:server-certificate/k8s-cert

**Comment by pahud** [comment]
Thanks @walkley
